version: "3"
services:
  app:
    build:
      context: .
      target: ci
    depends_on:
      - mysql
    environment:
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mysql:3306
      DATABASE_URL: mysql2://app:app@mysql/app?pool=10

  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
